import React, { createContext, useContext, useState, useEffect } from 'react';
import { storage } from '../lib/storage';
import { persistence } from '../lib/persistence';

const AuthContext = createContext();

const translations = {
  English: {
    dashboard: 'Dashboard',
    stock_control: 'Stock Control',
    financials: 'Financials',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    welcome_back: 'Welcome Back',
    today_revenue: "Today's Revenue",
    expected_from_sales: 'Expected from Sales',
    dairy_sales: 'Dairy Sales',
    liters_today: 'Liters Today',
    juice_sales: 'Juice Sales',
    cash_difference: 'Cash Difference',
    shortage: 'Shortage',
    excess: 'Excess',
    balanced: 'Balanced',
    no_audit_yet: 'No audit yet',
    profit_loss: 'Profit/Loss',
    revenue_selling_price: 'Revenue (Selling Price)',
    contribution: 'Contribution',
    attention_required: 'Attention Required',
    low_stock: 'Low Stock',
    reorder_immediately: 'Reorder Immediately',
    system_healthy: 'System Healthy',
    no_alerts: 'No alerts',
    product: 'Product',
    quantity_sold: 'Quantity Sold',
    balance: 'Balance',
    revenue: 'Revenue',
    profile_settings: 'Account Settings',
    profile_subtitle: 'Manage your profile and security credentials',
    username: 'Username',
    mobile_number: 'Mobile Number',
    language_preferences: 'Language Preferences',
    default: 'Default',
    security_password: 'Security & Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    update_password: 'Update Password',
    sign_out_msg: 'Sign out of your account',
    session_end_msg: 'Ends your active session',
    ready_to_leave: 'Ready to leave?',
    logout_warning: "You'll need to sign back in to access your dashboard and manage stock records.",
    yes_logout: 'Yes, Logout Now',
    stay_logged_in: 'Stay Logged In',
    liters_sold: 'Liters Sold',
    sales_data_empty: 'Sales data will appear here.',
    system_status_msg: "Here's what's happening at your shop today.",
    guest: 'Guest',
    no_role: 'No Role',
    system_login: 'System Login',
    login_subtitle: 'Enter your credentials to access the shop management system',
    login_button: 'Login to Account',
    select_language: 'Select Language',
    invalid_credentials: 'Invalid username or password',
    install_app_title: 'Install Aavinam App',
    install_app_desc: 'Get the best experience by installing our app on your home screen.',
    install_now: 'Install Now',

    // Sidebar & Navigation
    profile: 'Profile',
    staffs: 'Staff Management',
    admin: 'Admin',
    staff: 'Staff',
    system_config: 'System Configuration',
    pricing: 'Pricing',
    products: 'Products',
    logs: 'Activity Logs',

    // Common Actions
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    confirm: 'Confirm',
    update: 'Update',
    share: 'Share',
    export: 'Export',
    import: 'Import',
    search: 'Search',
    all_categories: 'All Categories',
    add: 'Add',
    remove: 'Remove',
    reset: 'Reset',
    edit: 'Edit',

    // Stock Control
    stock_control_system: 'Stock Control System',
    track_refrigeration: 'Track refrigeration and milk volumes in real-time',
    opening_stock: 'Opening Stock',
    fresh_stock: 'Fresh Stock',
    record_sale: 'Record Sale',
    daily_schedule_checks: 'Daily Schedule Checks',
    staff_updates_msg: 'Hourly checks required',
    update_level: 'Update Level',
    todays_stock_summary: "Today's Stock Summary",
    low_level: 'Low Level',
    todays_logs: "Today's Logs",
    time: 'Time',
    type: 'Type',
    value: 'Value',
    actions: 'Actions',
    danger_zone: 'Danger Zone',
    confirm_daily_reset: 'Confirm Daily Reset?',
    reset_warning: 'This will wipe all logs and sales for today. This action is irreversible.',
    reset_everything: 'Reset Everything',
    clear_today_data: "Clear Today's Data",
    clear_data_subtitle: 'Reset all stock logs, sales records, and cash entries for today.',
    new_entry: 'New entry',
    update_category: 'Update Category',
    select_product: 'Select Product',
    choose_product: 'Choose product...',
    qty_added_liter: 'Quantity Added (Liters)',
    qty_sold_liter: 'Quantity Sold (Liters)',
    current_stock_liter: 'Current Stock Level (Liters)',
    quantity_liter: 'Quantity (Liters)',
    sale_unit: 'Sale Unit',
    liter: 'Liter',
    per_glass: 'Per Glass',
    reason_note_mandatory: 'Reason / Note (Mandatory)',
    provide_reason_placeholder: 'Provide a reason for this entry...',
    save_entry: 'Save Entry',
    confirm_deletion: 'Confirm Deletion',
    confirm_delete_audit_warning: 'Are you sure you want to permanently delete this audit record? It will be removed from system history.',
    confirm_delete_product_warning: 'Are you sure you want to delete this product? This will also remove related historical data.',
    confirm_delete_staff_warning: 'Are you sure you want to remove this staff member? Their access will be revoked immediately.',
    confirm_delete_log_warning: 'Are you sure you want to delete this stock entry? This will affect the daily balance calculation.',
    confirm_delete_price_log_warning: 'This will permanently remove this price change record from the audit trail.',
    confirm_delete_expense_warning: 'Are you sure you want to delete this expense entry? This will update your calculated net profit.',
    confirm_delete_cash_audit_warning: 'Are you sure you want to delete this daily cash audit entry?',
    yes_delete: 'Yes, Delete',
    confirm_logout: 'Wait! Are you sure?',

    // Financial & Cash
    financial_control: 'Sales & Financial Control',
    financial_subtitle: 'Monitor revenue, manage expenses, and verify cash collection',
    record_expense: 'Record Expense',
    daily_cash_count: 'Daily Cash Count',
    expected_revenue_today: 'Expected Revenue (Today)',
    dairy: 'Dairy',
    juice: 'Juice',
    expenses_today: 'Expenses (Today)',
    recorded_throughout_day: 'Recorded throughout the day',
    estimated_net_profit: 'Estimated Net Profit',
    excludes_gst: 'Excludes GST & unpaid dues',
    daily_cash_audits: 'Daily Cash Audits',
    no_cash_counts: 'No cash counts submitted yet.',
    audited_by: 'Audited by',
    expected: 'Expected',
    actual_count: 'Actual Count',
    difference: 'Difference',
    audit_notes_optional: 'Audit Notes (Optional)',
    reason_for_discrepancy: 'e.g. Reason for excess or shortage...',
    confirm_audit: 'Confirm Audit',
    category: 'Category',
    amount_rupee: 'Amount (₹)',
    note_details: 'Note / Details',
    what_was_this_for: 'What was this for?',
    save_expense: 'Save Expense',
    daily_cash_audit: 'Daily Cash Audit',
    expected_physical_cash: 'Expected Physical Cash (Today)',
    revenue_minus_expenses: 'Calculated as Total Revenue minus Expenses',
    manually_counted_cash: 'Manually Counted Cash (₹)',
    enter_amount: 'Enter amount...',
    expense_tracker: 'Expense Tracker',
    date_category: 'Date & Category',
    no_expenses_recorded: 'No expenses recorded.',

    // Reports & Analytics
    reports_analytics: 'Reports & Business Analytics',
    reports_subtitle: 'Analyze sales performance and export data for accounting',
    share_report: 'Share Report',
    download_pdf: 'Download PDF',
    export_csv: 'Export CSV',
    period_summary: 'Period Summary',
    total_sales: 'Total Sales',
    mobile_number_admin: 'Mobile Number (leave blank for Admin)',
    admin_placeholder: 'Admin Mobile',
    enter_10_digit: 'Enter 10-digit mobile number',
    standard: 'Standard',
    download_analysis_pdf: 'Download Analysis PDF',
    secure_analytics_sharing: 'Secure Analytics Sharing',
    today: 'Today',
    yesterday: 'Yesterday',
    last_7_days: 'Last 7 Days',
    this_month: 'This Month',
    custom_range: 'Custom Range',
    time_period: 'Time Period',
    start_date: 'Start Date',
    end_date: 'End Date',
    generated_for: 'Generated for',
    total_period_revenue: 'Total Period Revenue',
    total_expenses: 'Total Expenses',
    net_profit: 'Net Profit',
    category_distribution: 'Category Distribution',
    no_sales_visualize: 'No sales data to visualize',
    product_performance: 'Product Performance details',
    unit_price: 'Unit Price',
    no_sales_recorded: 'No sales recorded for this period.',

    // Settings & System
    system_configuration: 'System Configuration',
    operational_schedule: 'Operational Schedule',
    staff_record_checkpoints: 'Staff will record stock levels at these checkpoints',
    add_slot: 'Add Slot',
    confirm_deletion_timeslot: 'Are you sure you want to delete this operational time slot?',
    no_time_slots: 'No time slots defined.',
    operational_preferences: 'Operational Preferences',
    enable_gst: 'Enable GST Reporting',
    gst_subtitle: 'Automatically include GST (18%) in financial reports.',
    data_safety_cloud: 'Data Safety & Cloud',
    local_browser_storage: 'Your data is stored locally in your browser.',
    storage_safety: 'Storage Safety',
    storage_status: 'Storage Status',
    persistent: 'Persistent (Protected)',
    best_effort: 'Best-effort (Risk of deletion)',
    request_persistence: 'Enable Data Protection',
    persistence_desc: 'Ensures the browser never automatically deletes your data even when disk space is low.',
    storage_usage: 'Storage Usage',
    total_quota: 'Total Quota',
    persistence_granted: 'Data protection enabled! Your records are now safe from automatic deletion.',
    persistence_denied: 'Could not enable data protection. This might happen if your browser settings prevent it.',
    export_full_backup: 'Export Full System Backup',
    or: 'OR',
    restore_from_backup: 'Restore From Backup',
    maintenance_zone: 'Maintenance Zone',
    irreversible_operations: 'Irreversible operations — proceed with caution',
    confirmed_factory_reset: 'Confirm Factory Reset?',
    wipe_everything: 'Yes, Wipe EVERYTHING',
    high_risk: 'HIGH RISK',
    factory_reset_subtitle: 'Permanently wipes all data — Products, Pricing, Logs, Financials, and Settings.',
    delete_warning_list: 'The following will be permanently deleted:',
    products_pricing_history: 'All Products and Pricing history',
    stock_sales_records: 'All Stock Logs and Sales Records',
    financial_expenses_audits: 'Financial data, Expenses and Cash Audits',
    activity_system_settings: 'Activity Logs and System Settings',
    start_reset_process: 'Start Reset Process',
    factory_reset_system: 'Factory Reset System',
    audit_trail: 'Audit Trail',
    audit_subtitle: 'Immutable logs for system operations and security',
    reset_logs: 'Reset Logs',
    admin_only_access: 'Admin Only Access',
    search_logs_placeholder: 'Search by user or details...',
    stock_updates: 'Stock Updates',
    price_changes: 'Price Changes',
    reset_actions: 'Reset Actions',
    no_activities_recorded: 'No activities recorded yet.',
    try_broadening_search: 'Try broadening your search or filter.',
    view_details: 'View Details',
    audit_record_details: 'Audit Record Details',
    action_type: 'Action Type',
    timestamp: 'Timestamp',
    performer_info: 'Performer Information',
    system_log_entry: 'System Log Entry',
    entry_id: 'Entry ID',
    reset_audit_logs: 'Reset Audit Logs',
    reset_logs_warning_subtitle: 'Select the date range of logs you want to permanently delete. This action cannot be reversed.',
    date_range: 'Date Range',
    clear_selected: 'Clear Selected',
    pricing_control: 'Pricing Control',
    pricing_subtitle: 'Manage product selling prices and track historical changes',
    active_selling_prices: 'Active Selling Prices',
    search_products_placeholder: 'Search products...',
    liter_price: 'Liter Price',
    glass_price: 'Glass Price',
    update_price_btn: 'Update Price',
    price_audit_log: 'Price Audit Log',
    no_price_changes: 'No price changes recorded yet.',
    increase: 'Increase',
    decrease: 'Decrease',
    update_selling_price: 'Update Selling Price',
    product_management: 'Product Management',
    product_mgmt_subtitle: 'Manage your shop inventory and categorization',
    add_new_product: 'Add New Product',
    product_details: 'Product Details',
    total_sold: 'Total Sold',
    total_revenue: 'Total Revenue',
    no_products_found: 'No products found matching your criteria.',
    edit_product: 'Edit Product',
    create_product: 'Create Product',
    product_history: 'Product History',
    staff_management_subtitle: 'Create and manage staff accounts for shop operations',
    add_new_staff: 'Add New Staff Member',
    search_staff_placeholder: 'Search staff by username or mobile...',
    staff_info: 'Staff Info',
    role: 'Role',
    status: 'Status',
    active: 'Active',
    enabled: 'Enabled',
    disabled: 'Disabled',
    edit_staff: 'Edit Staff Member',
    enter_username: 'Enter username',
    enter_password: 'Enter password',
    delete_user: 'Delete User',
    access_denied: 'Access Denied',
    access_denied_subtitle: 'Only administrators can manage staff members.',
    save_all_changes: 'Save All Changes',
    activity_description: 'Activity Description',
    confirm_reset: 'Confirm Reset',
    yes_reset_now: 'Yes, Reset Now',
    factory_reset: 'Factory Reset',
    password: 'Password',
    mobile: 'Mobile',
    optional: 'Optional',
    not_set: 'Not set',
    no_staff_members_found: 'No staff members found matching your search.',
    update_staff: 'Update Staff Member',
    create_staff: 'Create Staff Member',
    staff_management: 'Staff Management',
    new_entries: 'New Entries',
    all_activities: 'All Activities',
    sale: 'Sale',
    fresh: 'Fresh',
    opening: 'Opening',
    check: 'Check',
    adjustment: 'Adjustment',
    scheduled: 'Scheduled',
    liter_abbr: 'L',
    glass_abbr: 'G',
    rent: 'Rent',
    electricity: 'Electricity',
    staff_salary: 'Staff Salary',
    water_bill: 'Water Bill',
    maintenance: 'Maintenance',
    transport: 'Transport',
    misc: 'Misc',
    amount: 'Amount',
    profit: 'Profit',
    products_sold: 'Products sold',
    irreversible_action_warning: 'This action is irreversible!',
    at_least_4_chars: 'At least 4 characters',
    username_min_3: 'Username must be at least 3 characters.',
    invalid_mobile_10: 'Please enter a valid 10-digit mobile number.',
    password_mismatch: 'New passwords do not match!',
    password_min_4: 'Password must be at least 4 characters.',
    username_exists: 'Username already exists. Please choose another one.',
    audit_discrepancy: 'Audit Discrepancy',
    in_last_audit: 'in last audit'
  },
  Tamil: {
    dashboard: 'டாஷ்போர்டு',
    stock_control: 'இருப்பு',
    financials: 'நிதி',
    reports: 'அறிக்கைகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    welcome_back: 'மீண்டும் வருக',
    today_revenue: 'இன்றைய வருமானம்',
    expected_from_sales: 'விற்பனையால் எதிர்பார்க்கப்படுவது',
    dairy_sales: 'பால் விற்பனை',
    liters_today: 'இன்று லிட்டர்கள்',
    juice_sales: 'ஜூஸ் விற்பனை',
    cash_difference: 'ரொக்க வித்தியாசம்',
    shortage: 'பற்றாக்குறை',
    excess: 'உபரி',
    balanced: 'சரி',
    no_audit_yet: 'தணிக்கை செய்யப்படவில்லை',
    profit_loss: 'லாபம்/நஷ்டம்',
    revenue_selling_price: 'வருமானம் (விற்பனை விலை)',
    contribution: 'பங்களிப்பு',
    attention_required: 'கவனம் தேவை',
    low_stock: 'குறைந்த இருப்பு',
    reorder_immediately: 'உடனடியாக ஆர்டர் செய்யவும்',
    system_healthy: 'சாதனம் சீராக உள்ளது',
    no_alerts: 'எச்சரிக்கைகள் இல்லை',
    product: 'பொருள்',
    quantity_sold: 'விற்பனையான அளவு',
    balance: 'மீதி',
    revenue: 'வருமானம்',
    profile_settings: 'கணக்கு அமைப்புகள்',
    profile_subtitle: 'உங்கள் சுயவிவரம் மற்றும் பாதுகாப்பு சான்றுகளை நிர்வகிக்கவும்',
    username: 'பயனர் பெயர்',
    mobile_number: 'கைபேசி எண்',
    language_preferences: 'மொழி விருப்பங்கள்',
    default: 'இயல்புநிலை',
    security_password: 'பாதுகாப்பு மற்றும் கடவுச்சொல்',
    current_password: 'தற்போதைய கடவுச்சொல்',
    new_password: 'புதிய கடவுச்சொல்',
    confirm_password: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    update_password: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
    sign_out_msg: 'உங்கள் கணக்கிலிருந்து வெளியேறவும்',
    session_end_msg: 'உங்கள் செயலில் உள்ள அமர்வை முடிக்கிறது',
    ready_to_leave: 'வெளியேறத் தயாரா?',
    logout_warning: 'உங்கள் டாஷ்போர்டை அணுகவும் மற்றும் இருப்பு பதிவுகளை நிர்வகிக்கவும் நீங்கள் மீண்டும் உள்நுழைய வேண்டும்.',
    yes_logout: 'ஆம், இப்போது வெளியேறு',
    stay_logged_in: 'உள்ளேயே இரு',
    liters_sold: 'லிட்டர் விற்பனை',
    sales_data_empty: 'விற்பனை தரவு இங்கே தோன்றும்.',
    system_status_msg: 'இன்று உங்கள் கடையில் என்ன நடக்கிறது என்பது இங்கே.',
    guest: 'விருந்தினர்',
    no_role: 'பதவி இல்லை',
    system_login: 'கணினி உள்நுழைவு',
    login_subtitle: 'கடை மேலாண்மை அமைப்பை அணுக உங்கள் விவரங்களை உள்ளிடவும்',
    login_button: 'கணக்கில் உள்நுழைக',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    invalid_credentials: 'தவறான பயனர் பெயர் அல்லது கடவுச்சொல்',
    install_app_title: 'ஆவினம் செயலியை நிறுவவும்',
    install_app_desc: 'சிறந்த அனுபவத்தைப் பெற உங்கள் முகப்புத் திரையில் எங்கள் செயலியை நிறுவவும்.',
    install_now: 'இப்போதே நிறுவு',

    // Sidebar & Navigation
    profile: 'சுயவிவரம்',
    staffs: 'ஊழியர் மேலாண்மை',
    admin: 'நிர்வாகி',
    staff: 'ஊழியர்',
    system_config: 'கணினி உள்ளமைப்பு',
    pricing: 'விலை நிர்ணயம்',
    products: 'பொருட்கள்',
    logs: 'செயல்பாட்டு பதிவுகள்',

    // Common Actions
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    delete: 'நீக்கு',
    confirm: 'உறுதிப்படுத்து',
    update: 'புதுப்பி',
    share: 'பகிர்',
    export: 'ஏற்றுமதி',
    import: 'இறக்குமதி',
    search: 'தேடு',
    all_categories: 'அனைத்து பிரிவுகள்',
    add: 'சேர்க்க',
    remove: 'அகற்று',
    reset: 'மீட்டமை',
    edit: 'திருத்து',

    // Stock Control
    stock_control_system: 'இருப்பு மேலாண்மை முறை',
    track_refrigeration: 'குளிர்பதன மற்றும் பால் அளவைக் கண்காணிக்கவும்',
    opening_stock: 'ஆரம்ப இருப்பு',
    fresh_stock: 'புதிய இருப்பு',
    record_sale: 'விற்பனை பதிவு',
    daily_schedule_checks: 'தினசரி அட்டவணை சரிபார்ப்பு',
    staff_updates_msg: 'மணிநேர சரிபார்ப்புகள் தேவை',
    update_level: 'அளவை புதுப்பி',
    todays_stock_summary: 'இன்றைய இருப்பு சுருக்கம்',
    low_level: 'குறைந்த அளவு',
    todays_logs: 'இன்றைய பதிவுகள்',
    time: 'நேரம்',
    type: 'வகை',
    value: 'மதிப்பு',
    actions: 'செயல்கள்',
    danger_zone: 'அபாய பகுதி',
    confirm_daily_reset: 'தினசரி மீட்டமைப்பை உறுதிப்படுத்தவா?',
    reset_warning: 'இது இன்றைய அனைத்து பதிவுகளையும் விற்பனையையும் அழிக்கும். இதை மாற்ற முடியாது.',
    reset_everything: 'அனைத்தையும் மீட்டமை',
    clear_today_data: 'இன்றைய தரவை அழி',
    clear_data_subtitle: 'இன்றைய அனைத்து இருப்பு பதிவுகள், விற்பனை மற்றும் ரொக்க பதிவுகளை மீட்டமைக்கவும்.',
    new_entry: 'புதிய பதிவு',
    update_category: 'பிரிவைப் புதுப்பி',
    select_product: 'பொருளைத் தேர்ந்தெடுக்கவும்',
    choose_product: 'பொருளைத் தேர்வு செய்யவும்...',
    qty_added_liter: 'சேர்க்கப்பட்ட அளவு (லிட்டர்)',
    qty_sold_liter: 'விற்பனையான அளவு (லிட்டர்)',
    current_stock_liter: 'தற்போதைய இருப்பு அளவு (லிட்டர்)',
    quantity_liter: 'அளவு (லிட்டர்)',
    sale_unit: 'விற்பனை அலகு',
    liter: 'லிட்டர்',
    per_glass: 'ஒரு கிளாஸ்',
    reason_note_mandatory: 'காரணம் / குறிப்பு (கட்டாயம்)',
    provide_reason_placeholder: 'இந்த பதிவிற்கான காரணத்தை வழங்கவும்...',
    save_entry: 'பதிவைச் சேமி',
    confirm_deletion: 'நிச்சயமாக நீக்கவா?',
    confirm_delete_audit_warning: 'இந்த தணிக்கைப் பதிவை நிரந்தரமாக நீக்க விரும்புகிறீர்களா? இது கணினி வரலாற்றிலிருந்து அகற்றப்படும்.',
    confirm_delete_product_warning: 'இந்தப் பொருளை நீக்க விரும்புகிறீர்களா? இது தொடர்பான வரலாற்றுத் தரவுகளும் அகற்றப்படும்.',
    confirm_delete_staff_warning: 'இந்த ஊழியரை நீக்க விரும்புகிறீர்களா? அவர்களின் அணுகல் உடனடியாக ரத்து செய்யப்படும்.',
    confirm_delete_log_warning: 'இந்த இருப்புப் பதிவை நீக்க விரும்புகிறீர்களா? இது தினசரி இருப்பு கணக்கீட்டைப் பாதிக்கும்.',
    confirm_delete_price_log_warning: 'இது தணிக்கை தடயத்திலிருந்து இந்த விலை மாற்றப் பதிவை நிரந்தரமாக அகற்றும்.',
    confirm_delete_expense_warning: 'இந்தச் செலவுப் பதிவை நீக்க விரும்புகிறீர்களா? இது உங்கள் நிகர லாபக் கணக்கீட்டைப் பாதிக்கும்.',
    confirm_delete_cash_audit_warning: 'இந்தத் தினசரி ரொக்கத் தணிக்கைப் பதிவை நீக்க விரும்புகிறீர்களா?',
    yes_delete: 'ஆம், நீக்கு',
    confirm_logout: 'பொறுங்கள்! நிச்சயமாக வெளியேற வேண்டுமா?',

    // Financial & Cash
    financial_control: 'விற்பனை மற்றும் நிதி கட்டுப்பாடு',
    financial_subtitle: 'வருமானத்தை கண்காணிக்கவும், செலவுகளை நிர்வகிக்கவும் மற்றும் பணத்தை சரிபார்க்கவும்',
    record_expense: 'செலவு பதிவு',
    daily_cash_count: 'தினசரி ரொக்க எண்ணிக்கை',
    expected_revenue_today: 'எதிர்பார்க்கப்படும் வருவாய் (இன்று)',
    dairy: 'பால் பண்ணை',
    juice: 'ஜூஸ்',
    expenses_today: 'செலவுகள் (இன்று)',
    recorded_throughout_day: 'நாள் முழுவதும் பதிவு செய்யப்பட்டது',
    estimated_net_profit: 'மதிப்பிடப்பட்ட நிகர லாபம்',
    excludes_gst: 'ஜிஎஸ்டி மற்றும் செலுத்தப்படாத நிலுவைகள் தவிர்த்து',
    daily_cash_audits: 'தினசரி ரொக்க தணிக்கைகள்',
    no_cash_counts: 'இன்னும் ரொக்க எண்ணிக்கைகள் சமர்ப்பிக்கப்படவில்லை.',
    audited_by: 'தணிக்கை செய்தவர்',
    expected: 'எதிர்பார்க்கப்பட்டது',
    actual_count: 'உண்மையான எண்ணிக்கை',
    difference: 'வித்தியாசம்',
    audit_notes_optional: 'தணிக்கை குறிப்புகள் (விருப்பம்)',
    reason_for_discrepancy: 'எ.கா. உபரி அல்லது பற்றாக்குறைக்கான காரணம்...',
    confirm_audit: 'தணிக்கையை உறுதிப்படுத்து',
    category: 'பிரிவு',
    amount_rupee: 'தொகை (₹)',
    note_details: 'குறிப்பு / விவரங்கள்',
    what_was_this_for: 'இது எதற்காக?',
    save_expense: 'செலவைச் சேமி',
    daily_cash_audit: 'தினசரி ரொக்க தணிக்கை',
    expected_physical_cash: 'எதிர்பார்க்கப்படும் ரொக்கம் (இன்று)',
    revenue_minus_expenses: 'மொத்த வருவாய் கழித்தல் செலவுகள் என கணக்கிடப்படுகிறது',
    manually_counted_cash: 'கையால் எண்ணப்பட்ட ரொக்கம் (₹)',
    enter_amount: 'தொகையை உள்ளிடவும்...',
    expense_tracker: 'செலவு கண்காணிப்பு',
    date_category: 'தேதி மற்றும் பிரிவு',
    no_expenses_recorded: 'செலவுகள் எதுவும் பதிவு செய்யப்படவில்லை.',

    // Reports & Analytics
    reports_analytics: 'அறிக்கைகள் மற்றும் வணிக பகுப்பாய்வு',
    reports_subtitle: 'விற்பனை செயல்திறனை பகுப்பாய்வு செய்யவும் மற்றும் ஏலக்காய் தரவை ஏற்றுமதி செய்யவும்',
    share_report: 'அறிக்கையை பகிர்',
    download_pdf: 'PDF தரவிறக்கம்',
    export_csv: 'CSV ஏற்றுமதி',
    period_summary: 'கால சுருக்கம்',
    total_sales: 'மொத்த விற்பனை',
    mobile_number_admin: 'கைபேசி எண் (நிர்வாகிக்கு காலியாக விடவும்)',
    admin_placeholder: 'நிர்வாகி கைபேசி',
    enter_10_digit: '10 இலக்க கைபேசி எண்ணை உள்ளிடவும்',
    standard: 'தரமானது',
    download_analysis_pdf: 'பகுப்பாய்வு PDF தரவிறக்கம்',
    secure_analytics_sharing: 'பாதுகாப்பான பகுப்பாய்வு பகிர்வு',
    today: 'இன்று',
    yesterday: 'நேற்று',
    last_7_days: 'கடந்த 7 நாட்கள்',
    this_month: 'இந்த மாதம்',
    custom_range: 'தனிப்பயன் காலம்',
    time_period: 'கால அளவு',
    start_date: 'ஆரம்ப தேதி',
    end_date: 'முடிவு தேதி',
    generated_for: 'இதற்காக உருவாக்கப்பட்டது',
    total_period_revenue: 'மொத்த கால வருவாய்',
    total_expenses: 'மொத்த செலவுகள்',
    net_profit: 'நிகர லாபம்',
    category_distribution: 'பிரிவு விநியோகம்',
    no_sales_visualize: 'காண்பிக்க விற்பனை தரவு இல்லை',
    product_performance: 'பொருள் செயல்திறன் விவரங்கள்',
    unit_price: 'அலகு விலை',
    no_sales_recorded: 'இந்த காலத்தில் விற்பனை எதுவும் பதிவு செய்யப்படவில்லை.',

    // Settings & System
    system_configuration: 'கணினி உள்ளமைப்பு',
    operational_schedule: 'செயல்பாட்டு அட்டவணை',
    staff_record_checkpoints: 'ஊழியர்கள் இந்த நேரங்களில் இருப்பைப் பதிவு செய்வார்கள்',
    add_slot: 'நேரத்தைச் சேர்',
    confirm_deletion_timeslot: 'இந்த செயல்பாட்டு நேரத்தை நீக்க விரும்புகிறீர்களா?',
    no_time_slots: 'நேரங்கள் எதுவும் வரையறுக்கப்படவில்லை.',
    operational_preferences: 'செயல்பாட்டு விருப்பங்கள்',
    enable_gst: 'ஜிஎஸ்டி அறிக்கையை இயக்கு',
    gst_subtitle: 'நிதி அறிக்கைகளில் தானாகவே ஜிஎஸ்டி (18%) சேர்க்கவும்.',
    data_safety_cloud: 'தரவு பாதுகாப்பு மற்றும் கிளவுட்',
    local_browser_storage: 'உங்கள் தரவு உங்கள் உலாவியில் உள்நாட்டில் சேமிக்கப்படுகிறது.',
    storage_safety: 'தரவுப் பாதுகாப்பு',
    storage_status: 'சேமிப்பக நிலை',
    persistent: 'நிலைத்தன்மை (பாதுகாக்கப்பட்டது)',
    best_effort: 'சாதாரண நிலை (அழிக்கப்பட வாய்ப்புள்ளது)',
    request_persistence: 'தரவுப் பாதுகாப்பை இயக்கவும்',
    persistence_desc: 'மெமரி குறைவாக இருந்தாலும் உலாவி தானாகவே உங்கள் தரவை அழிக்காது என்பதை உறுதிப்படுத்துகிறது.',
    storage_usage: 'பயன்படுத்தப்பட்ட அளவு',
    total_quota: 'மொத்த அளவு',
    persistence_granted: 'தரவு பாதுகாப்பு வெற்றிகரமாக இயக்கப்பட்டது!',
    persistence_denied: 'தரவு பாதுகாப்பை இயக்க முடியவில்லை.',
    export_full_backup: 'முழு கணினி காப்புப்பிரதியை ஏற்றுமதி செய்',
    or: 'அல்லது',
    restore_from_backup: 'காப்புப்பிரதியிலிருந்து மீட்டமை',
    maintenance_zone: 'பராமரிப்பு பகுதி',
    irreversible_operations: 'மாற்ற முடியாத செயல்பாடுகள் — எச்சரிக்கையுடன் தொடரவும்',
    confirmed_factory_reset: 'தொழிற்சாலை மீட்டமைப்பை உறுதிப்படுத்தவா?',
    wipe_everything: 'ஆம், அனைத்தையும் அழி',
    high_risk: 'அதிக ஆபத்து',
    factory_reset_subtitle: 'பொருட்கள், விலை நிர்ணயம், பதிவுகள், நிதி மற்றும் அமைப்புகள் அனைத்தையும் நிரந்தரமாக அழிக்கும்.',
    delete_warning_list: 'பின்வருவன நிரந்தரமாக நீக்கப்படும்:',
    products_pricing_history: 'அனைத்து பொருட்கள் மற்றும் விலை வரலாறு',
    stock_sales_records: 'அனைத்து இருப்பு பதிவுகள் மற்றும் விற்பனை பதிவுகள்',
    financial_expenses_audits: 'நிதி தரவு, செலவுகள் மற்றும் ரொக்க தணிக்கைகள்',
    activity_system_settings: 'செயல்பாட்டு பதிவுகள் மற்றும் கணினி அமைப்புகள்',
    start_reset_process: 'மீட்டமைப்பு செயல்முறையைத் தொடங்கு',
    factory_reset_system: 'கணினியை தொழிற்சாலை மீட்டமை',
    audit_trail: 'தணிக்கை தடயங்கள்',
    audit_subtitle: 'கணினி செயல்பாடுகள் மற்றும் பாதுகாப்பிற்கான மாற்ற முடியாத பதிவுகள்',
    reset_logs: 'பதிவுகளை மீட்டமை',
    admin_only_access: 'நிர்வாகிக்கு மட்டும் அனுமதி',
    search_logs_placeholder: 'பயனர் அல்லது விவரங்கள் மூலம் தேடுங்கள்...',
    stock_updates: 'இருப்பு புதுப்பிப்புகள்',
    price_changes: 'விலை மாற்றங்கள்',
    reset_actions: 'மீட்டமைப்பு செயல்கள்',
    no_activities_recorded: 'இன்னும் செயல்பாடுகள் எதுவும் பதிவு செய்யப்படவில்லை.',
    try_broadening_search: 'உங்கள் தேடல் அல்லது வடிகட்டியை விரிவுபடுத்த முயற்சிக்கவும்.',
    view_details: 'விவரங்களைக் காண்க',
    audit_record_details: 'தணிக்கைப் பதிவு விவரங்கள்',
    action_type: 'செயல் வகை',
    timestamp: 'நேர முத்திரை',
    performer_info: 'செய்தவர் விவரங்கள்',
    system_log_entry: 'கணினி பதிவு உள்ளீடு',
    entry_id: 'பதிவு ஐடி',
    reset_audit_logs: 'தணிக்கை பதிவுகளை மீட்டமை',
    reset_logs_warning_subtitle: 'நீங்கள் நிரந்தரமாக நீக்க விரும்பும் பதிவுகளின் தேதி வரம்பைத் தேர்ந்தெடுக்கவும். இந்தச் செயலை மாற்ற முடியாது.',
    date_range: 'தேதி வரம்பு',
    clear_selected: 'தேர்ந்தெடுக்கப்பட்டதை அழி',
    pricing_control: 'விலை நிர்ணய கட்டுப்பாடு',
    pricing_subtitle: 'பொருள் விற்பனை விலைகளை நிர்வகிக்கவும் மற்றும் வரலாற்று மாற்றங்களைக் கண்காணிக்கவும்',
    active_selling_prices: 'செயலில் உள்ள விற்பனை விலைகள்',
    search_products_placeholder: 'பொருட்களைத் தேடுங்கள்...',
    liter_price: 'லிட்டர் விலை',
    glass_price: 'கிளாஸ் விலை',
    update_price_btn: 'விலையை புதுப்பி',
    price_audit_log: 'விலை தணிக்கை பதிவு',
    no_price_changes: 'விலை மாற்றங்கள் எதுவும் இன்னும் பதிவு செய்யப்படவில்லை.',
    increase: 'அதிகரிப்பு',
    decrease: 'குறைவு',
    update_selling_price: 'விற்பனை விலையைப் புதுப்பி',
    product_management: 'பொருள் மேலாண்மை',
    product_mgmt_subtitle: 'உங்கள் கடை இருப்பு மற்றும் வகைப்பாட்டை நிர்வகிக்கவும்',
    add_new_product: 'புதிய பொருளைச் சேர்',
    product_details: 'பொருள் விவரங்கள்',
    total_sold: 'மொத்த விற்பனை',
    total_revenue: 'மொத்த வருமானம்',
    no_products_found: 'உங்கள் தேடலுக்குப் பொருத்தமான பொருட்கள் எதுவும் இல்லை.',
    edit_product: 'பொருளைத் திருத்து',
    create_product: 'பொருளை உருவாக்கு',
    product_history: 'பொருள் வரலாறு',
    staff_management_subtitle: 'கடை செயல்பாடுகளுக்கு ஊழியர் கணக்குகளை உருவாக்கி நிர்வகிக்கவும்',
    add_new_staff: 'புதிய ஊழியரைச் சேர்',
    search_staff_placeholder: 'பயனர் பெயர் அல்லது கைபேசி மூலம் ஊழியரைத் தேடுங்கள்...',
    staff_info: 'ஊழியர் விவரம்',
    role: 'பதவி',
    status: 'நிலை',
    active: 'செயலில்',
    enabled: 'செயல்படுத்தப்பட்டது',
    disabled: 'முடக்கப்பட்டது',
    edit_staff: 'ஊழியரைத் திருத்து',
    enter_username: 'பயனர் பெயரை உள்ளிடவும்',
    enter_password: 'கடவுச்சொல்லை உள்ளிடவும்',
    delete_user: 'பயனரை நீக்கு',
    access_denied: 'அனுமதி மறுக்கப்பட்டது',
    access_denied_subtitle: 'நிர்வாகிகள் மட்டுமே ஊழியர்களை நிர்வகிக்க முடியும்.',
    save_all_changes: 'அனைத்து மாற்றங்களையும் சேமி',
    activity_description: 'செயல்பாடு விவரம்',
    confirm_reset: 'மீட்டமைப்பை உறுதிப்படுத்து',
    yes_reset_now: 'ஆம், இப்போது மீட்டமை',
    factory_reset: 'தொழிற்சாலை மீட்டமைப்பு',
    password: 'கடவுச்சொல்',
    mobile: 'கைபேசி',
    optional: 'விருப்பமானது',
    not_set: 'அமைக்கப்படவில்லை',
    no_staff_members_found: 'உங்கள் தேடலுக்குப் பொருத்தமான ஊழியர்கள் யாரும் இல்லை.',
    update_staff: 'ஊழியரைத் புதுப்பி',
    create_staff: 'ஊழியரை உருவாக்கவும்',
    staff_management: 'ஊழியர் மேலாண்மை',
    new_entries: 'புதிய உள்ளீடுகள்',
    all_activities: 'அனைத்து செயல்பாடுகள்',
    sale: 'விற்பனை',
    fresh: 'புதியது',
    opening: 'துவக்க இருப்பு',
    check: 'சரிபார்ப்பு',
    adjustment: 'சரிசெய்தல்',
    scheduled: 'திட்டமிடப்பட்ட',
    liter_abbr: 'லி',
    glass_abbr: 'கி',
    rent: 'வாடகை',
    electricity: 'மின்சாரம்',
    staff_salary: 'ஊழியர் சம்பளம்',
    water_bill: 'தண்ணீர் கட்டணம்',
    maintenance: 'பராமரிப்பு',
    transport: 'போக்குவரத்து',
    misc: 'இதர',
    amount: 'தொகை',
    profit: 'லாபம்',
    products_sold: 'பொருட்கள் விற்கப்பட்டன',
    irreversible_action_warning: 'இந்தச் செயல் மீள முடியாதது!',
    at_least_4_chars: 'குறைந்தது 4 எழுத்துக்கள்',
    username_min_3: 'பயனர் பெயர் குறைந்தபட்சம் 3 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்.',
    invalid_mobile_10: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
    password_mismatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை!',
    password_min_4: 'கடவுச்சொல் குறைந்தபட்சம் 4 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்.',
    username_exists: 'பயனர் பெயர் ஏற்கனவே உள்ளது. தயவுசெய்து வேறு பெயர் தேர்ந்தெடுக்கவும்.',
    audit_discrepancy: 'தணிக்கை முரண்பாடு',
    in_last_audit: 'கடைசி தணிக்கையில்'
  },
  Hindi: {
    dashboard: 'डैशबोर्ड',
    stock_control: 'स्टॉक नियंत्रण',
    financials: 'वित्तीय',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    welcome_back: 'स्वागत है',
    today_revenue: 'आज का राजस्व',
    expected_from_sales: 'बिक्री से अपेक्षित',
    dairy_sales: 'डेयरी बिक्री',
    liters_today: 'आज लीटर',
    juice_sales: 'जूस की बिक्री',
    cash_difference: 'नकद अंतर',
    shortage: 'कमी',
    excess: 'अधिकता',
    balanced: 'संतुलित',
    no_audit_yet: 'अभी तक कोई ऑडिट नहीं',
    profit_loss: 'लाभ/हानि',
    revenue_selling_price: 'राजस्व (बिक्री मूल्य)',
    contribution: 'योगदान',
    attention_required: 'ध्यान देने की आवश्यकता',
    low_stock: 'कम स्टॉक',
    reorder_immediately: 'तुरंत पुन: व्यवस्थित करें',
    system_healthy: 'सिस्टम स्वस्थ है',
    no_alerts: 'कोई अलर्ट नहीं',
    product: 'उत्पाद',
    quantity_sold: 'बेची गई मात्रा',
    balance: 'शेष राशि',
    revenue: 'राजस्व',
    profile_settings: 'खाता सेटिंग्स',
    profile_subtitle: 'अपनी प्रोफ़ाइल और सुरक्षा क्रेडेंशियल प्रबंधित करें',
    username: 'उपयोगकर्ता नाम',
    mobile_number: 'मोबाइल नंबर',
    language_preferences: 'भाषा प्राथमिकताएं',
    default: 'डिफ़ॉल्ट',
    security_password: 'सुरक्षा और पासवर्ड',
    current_password: 'वर्तमान पासवर्ड',
    new_password: 'नया पासवर्ड',
    confirm_password: 'नए पासवर्ड की पुष्टि करें',
    update_password: 'पासवर्ड अपडेट करें',
    sign_out_msg: 'अपने खाते से साइन आउट करें',
    session_end_msg: 'आपके सक्रिय सत्र को समाप्त करता है',
    ready_to_leave: 'छोड़ने के लिए तैयार हैं?',
    logout_warning: 'आपको अपने डैशबोर्ड तक पहुंचने और स्टॉक रिकॉर्ड प्रबंधित करने के लिए वापस साइन इन करना होगा।',
    yes_logout: 'हाँ, अभी लॉग आउट करें',
    stay_logged_in: 'लॉग इन रहें',
    liters_sold: 'लीटर बेचे गए',
    sales_data_empty: 'बिक्री डेटा यहां दिखाई देगा।',
    system_status_msg: 'आज आपकी दुकान में क्या हो रहा है, यह यहाँ है।',
    guest: 'अतिथि',
    no_role: 'कोई भूमिका नहीं',
    system_login: 'सिस्टम लॉगिन',
    login_subtitle: 'दुकान प्रबंधन प्रणाली तक पहुँचने के लिए अपनी क्रेडेंशियल दर्ज करें',
    login_button: 'खाते में लॉगिन करें',
    select_language: 'भाषा चुनें',
    invalid_credentials: 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
    install_app_title: 'आविणम ऐप इंस्टॉल करें',
    install_app_desc: 'बेहतरीन अनुभव के लिए अपने होम स्क्रीन पर हमारा ऐप इंस्टॉल करें।',
    install_now: 'अभी इंस्टॉल करें',

    // Sidebar & Navigation
    profile: 'प्रोफ़ाइल',
    staffs: 'कर्मचारी प्रबंधन',
    system_config: 'सिस्टम कॉन्फ़िगरेशन',
    pricing: 'मूल्य निर्धारण',
    products: 'उत्पाद',
    logs: 'गतिविधि लॉग',

    // Common Actions
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    confirm: 'पुष्टि करें',
    update: 'अपडेट करें',
    share: 'साझा करें',
    export: 'निर्यात',
    import: 'आयात',
    search: 'खोजें',
    all_categories: 'सभी श्रेणियां',
    add: 'जोड़ें',
    remove: 'निकालें',
    reset: 'रीसेट',
    edit: 'संपादित करें',

    // Stock Control
    stock_control_system: 'स्टॉक नियंत्रण प्रणाली',
    track_refrigeration: 'वास्तविक समय में प्रशीतन और दूध की मात्रा को ट्रैक करें',
    opening_stock: 'ओपनिंग स्टॉक',
    fresh_stock: 'ताजा स्टॉक',
    record_sale: 'रिकॉर्ड बिक्री',
    daily_schedule_checks: 'दैनिक कार्यक्रम की जाँच',
    staff_updates_msg: 'हर घंटे जांच आवश्यक है',
    update_level: 'स्तर अपडेट करें',
    todays_stock_summary: 'आज का स्टॉक सारांश',
    low_level: 'निम्न स्तर',
    todays_logs: 'आज के लॉग',
    time: 'समय',
    type: 'प्रकार',
    value: 'मान',
    actions: 'क्रियाएं',
    danger_zone: 'खतरनाक क्षेत्र',
    confirm_daily_reset: 'दैनिक रीसेट की पुष्टि करें?',
    reset_warning: 'यह आज के सभी लॉग और बिक्री को मिटा देगा। यह क्रिया अपरिवर्तनीय है।',
    reset_everything: 'सब कुछ रीसेट करें',
    clear_today_data: 'आज का डेटा साफ़ करें',
    clear_data_subtitle: 'आज के सभी स्टॉक लॉग, बिक्री रिकॉर्ड और नकद प्रविष्टियों को रीसेट करें।',
    new_entry: 'नई प्रविष्टि',
    update_category: 'श्रेणी अपडेट करें',
    select_product: 'उत्पाद चुनें',
    choose_product: 'उत्पाद चुनें...',
    qty_added_liter: 'जोड़ी गई मात्रा (लीटर)',
    qty_sold_liter: 'बेची गई मात्रा (लीटर)',
    current_stock_liter: 'वर्तमान स्टॉक स्तर (लीटर)',
    quantity_liter: 'मात्रा (लीटर)',
    sale_unit: 'बिक्री इकाई',
    liter: 'लीटर',
    per_glass: 'प्रति गिलास',
    reason_note_mandatory: 'कारण / नोट (अनिवार्य)',
    provide_reason_placeholder: 'इस प्रविष्टि के लिए एक कारण प्रदान करें...',
    save_entry: 'प्रविष्टि सहेजें',
    confirm_deletion: 'क्या आप वाकई इसे हटाना चाहते हैं?',
    confirm_delete_audit_warning: 'क्या आप वाकई इस ऑडिट रिकॉर्ड को स्थायी रूप से हटाना चाहते हैं? इसे सिस्टम इतिहास से हटा दिया जाएगा।',
    confirm_delete_product_warning: 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं? इससे संबंधित ऐतिहासिक डेटा भी हटा दिया जाएगा।',
    confirm_delete_staff_warning: 'क्या आप वाकई इस स्टाफ सदस्य को हटाना चाहते हैं? उनकी पहुंच तुरंत रद्द कर दी जाएगी।',
    confirm_delete_log_warning: 'क्या आप वाकई इस स्टॉक एंट्री को हटाना चाहते हैं? यह दैनिक बैलेंस गणना को प्रभावित करेगा।',
    confirm_delete_price_log_warning: 'यह ऑडिट ट्रेल से इस मूल्य परिवर्तन रिकॉर्ड को स्थायी रूप से हटा देगा।',
    confirm_delete_expense_warning: 'क्या आप वाकई इस खर्च प्रविष्टि को हटाना चाहते हैं? यह आपके गणना किए गए शुद्ध लाभ को अपडेट कर देगा।',
    confirm_delete_cash_audit_warning: 'क्या आप वाकई इस दैनिक नकद ऑडिट प्रविष्टि को हटाना चाहते हैं?',
    yes_delete: 'हाँ, हटाएँ',
    confirm_logout: 'रुको! क्या आप वाकई बाहर निकलना चाहते हैं?',

    // Financial & Cash
    financial_control: 'बिक्री और वित्तीय नियंत्रण',
    financial_subtitle: 'राजस्व की निगरानी करें, खर्चों का प्रबंधन करें और नकद सत्यापन करें',
    record_expense: 'खर्च रिकॉर्ड करें',
    daily_cash_count: 'दैनिक नकद गणना',
    expected_revenue_today: 'अपेक्षित राजस्व (आज)',
    dairy: 'डेयरी',
    juice: 'जूस',
    expenses_today: 'खर्चे (आज)',
    recorded_throughout_day: 'दिन भर रिकॉर्ड किया गया',
    estimated_net_profit: 'अनुमानित शुद्ध लाभ',
    excludes_gst: 'इसमें जीएसटी और बकाया राशि शामिल नहीं है',
    daily_cash_audits: 'दैनिक नकद ऑडिट',
    no_cash_counts: 'अभी तक कोई नकद गणना सबमिट नहीं की गई है।',
    audited_by: 'ऑडिट किया गया',
    expected: 'अपेक्षित',
    actual_count: 'वास्तविक गणना',
    difference: 'अंतर',
    audit_notes_optional: 'ऑडिट नोट्स (वैकल्पिक)',
    reason_for_discrepancy: 'उदा. अधिकता या कमी का कारण...',
    confirm_audit: 'ऑडिट की पुष्टि करें',
    category: 'श्रेणी',
    amount_rupee: 'राशि (₹)',
    note_details: 'नोट / विवरण',
    what_was_this_for: 'यह किस लिए था?',
    save_expense: 'खर्च सहेजें',
    daily_cash_audit: 'दैनिक नकद ऑडिट',
    expected_physical_cash: 'अपेक्षित भौतिक नकद (आज)',
    revenue_minus_expenses: 'कुल राजस्व घटा खर्च के रूप में गणना की गई',
    manually_counted_cash: 'मैन्युअल रूप से गिना गया नकद (₹)',
    enter_amount: 'राशि दर्ज करें...',
    expense_tracker: 'खर्च ट्रैकर',
    date_category: 'दिनांक और श्रेणी',
    no_expenses_recorded: 'कोई खर्च रिकॉर्ड नहीं किया गया।',

    // Reports & Analytics
    reports_analytics: 'रिपोर्ट और व्यावसायिक विश्लेषण',
    reports_subtitle: 'बिक्री प्रदर्शन का विश्लेषण करें और लेखांकन के लिए डेटा निर्यात करें',
    share_report: 'रिपोर्ट साझा करें',
    download_pdf: 'PDF डाउनलोड करें',
    export_csv: 'CSV निर्यात करें',
    period_summary: 'अवधि सारांश',
    total_sales: 'कुल बिक्री',
    mobile_number_admin: 'मोबाइल नंबर (व्यवस्थापक के लिए खाली छोड़ें)',
    admin_placeholder: 'व्यवस्थापक मोबाइल',
    enter_10_digit: '10 अंकों का मोबाइल नंबर दर्ज करें',
    standard: 'मानक',
    download_analysis_pdf: 'विश्लेषण PDF डाउनलोड करें',
    secure_analytics_sharing: 'सुरक्षित विश्लेषण साझाकरण',
    today: 'आज',
    yesterday: 'कल',
    last_7_days: 'पिछले 7 दिन',
    this_month: 'इस महीने',
    custom_range: 'कस्टम रेंज',
    time_period: 'समय अवधि',
    start_date: 'आरंभ तिथि',
    end_date: 'अंतिम तिथि',
    generated_for: 'इसके लिए जनरेट किया गया',
    total_period_revenue: 'कुल अवधि राजस्व',
    total_expenses: 'कुल खर्च',
    net_profit: 'शुद्ध लाभ',
    category_distribution: 'श्रेणी वितरण',
    no_sales_visualize: 'विज़ुअलाइज़ करने के लिए कोई बिक्री डेटा नहीं',
    product_performance: 'उत्पाद प्रदर्शन विवरण',
    unit_price: 'इकाई मूल्य',
    no_sales_recorded: 'इस अवधि के लिए कोई बिक्री रिकॉर्ड नहीं की गई।',

    // Settings & System
    system_configuration: 'सिस्टम कॉन्फ़िगरेशन',
    operational_schedule: 'परिचालन कार्यक्रम',
    staff_record_checkpoints: 'कर्मचारी इन चौकियों पर स्टॉक स्तर रिकॉर्ड करेंगे',
    add_slot: 'स्लॉट जोड़ें',
    confirm_deletion_timeslot: 'क्या आप वाकई इस परिचालन समय स्लॉट को हटाना चाहते हैं?',
    no_time_slots: 'कोई समय स्लॉट परिभाषित नहीं है।',
    operational_preferences: 'परिचालन प्राथमिकताएं',
    enable_gst: 'जीएसटी रिपोर्टिंग सक्षम करें',
    gst_subtitle: 'वित्तीय रिपोर्ट में स्वचालित रूप से जीएसटी (18%) शामिल करें।',
    data_safety_cloud: 'डेटा सुरक्षा और क्लाउड',
    local_browser_storage: 'आपका डेटा आपके ब्राउज़र में स्थानीय रूप से संग्रहीत है।',
    storage_safety: 'डेटा सुरक्षा',
    storage_status: 'स्टोरेज की स्थिति',
    persistent: 'स्थायी (सुरक्षित)',
    best_effort: 'अस्थायी (हटाए जाने का जोखिम)',
    request_persistence: 'डेटा सुरक्षा सक्षम करें',
    persistence_desc: 'सुनिश्चित करता है कि डिस्क स्थान कम होने पर भी ब्राउज़र आपका डेटा कभी भी स्वचालित रूप से न हटाए।',
    storage_usage: 'स्टोरेज उपयोग',
    total_quota: 'कुल कोटा',
    persistence_granted: 'डेटा सुरक्षा सक्षम! आपके रिकॉर्ड अब सुरक्षित हैं।',
    persistence_denied: 'डेटा सुरक्षा सक्षम नहीं की जा सकी।',
    export_full_backup: 'पूर्ण सिस्टम बैकअप निर्यात करें',
    or: 'या',
    restore_from_backup: 'बैकअप से पुनर्स्थापित करें',
    maintenance_zone: 'रखरखाव क्षेत्र',
    irreversible_operations: 'अपरिवर्तनीय संचालन — सावधानी के साथ आगे बढ़ें',
    confirmed_factory_reset: 'फ़ैक्टरी रीसेट की पुष्टि करें?',
    wipe_everything: 'हाँ, सब कुछ मिटा दें',
    high_risk: 'उच्च जोखिम',
    factory_reset_subtitle: 'स्थायी रूप से सभी डेटा — उत्पाद, मूल्य निर्धारण, लॉग, वित्तीय और फ़ाइलें मिटा देता है।',
    delete_warning_list: 'निम्नलिखित स्थायी रूप से हटा दिए जाएंगे:',
    products_pricing_history: 'सभी उत्पाद और मूल्य निर्धारण इतिहास',
    stock_sales_records: 'सभी स्टॉक लॉग और बिक्री रिकॉर्ड',
    financial_expenses_audits: 'वित्तीय डेटा, खर्च और नकद ऑडिट',
    activity_system_settings: 'गतिविधि लॉग और सिस्टम सेटिंग्स',
    start_reset_process: 'रीसेट प्रक्रिया शुरू करें',
    factory_reset_system: 'सिस्टम फ़ैक्टरी रीसेट करें',
    audit_trail: 'ऑडिट ट्रेल',
    audit_subtitle: 'सिस्टम संचालन और सुरक्षा के लिए अपरिवर्तनीय लॉग',
    reset_logs: 'लॉग रीसेट करें',
    admin_only_access: 'केवल एडमिन एक्सेस',
    search_logs_placeholder: 'उपयोगकर्ता या विवरण द्वारा खोजें...',
    stock_updates: 'स्टॉक अपडेट',
    price_changes: 'मूल्य परिवर्तन',
    reset_actions: 'रीसेट क्रियाएं',
    no_activities_recorded: 'अभी तक कोई गतिविधियाँ रिकॉर्ड नहीं की गई हैं।',
    try_broadening_search: 'अपनी खोज या फ़िल्टर को व्यापक बनाने का प्रयास करें।',
    view_details: 'विवरण देखें',
    audit_record_details: 'ऑडिट रिकॉर्ड विवरण',
    action_type: 'क्रिया का प्रकार',
    timestamp: 'टाइमस्टैम्प',
    performer_info: 'कर्ता की जानकारी',
    system_log_entry: 'सिस्टम लॉग प्रविष्टि',
    entry_id: 'प्रविष्टि आईडी',
    reset_audit_logs: 'ऑडिट लॉग रीसेट करें',
    reset_logs_warning_subtitle: 'उन लॉग की दिनांक सीमा चुनें जिन्हें आप स्थायी रूप से हटाना चाहते हैं। इस क्रिया को वापस नहीं लिया जा सकता।',
    date_range: 'दिनांक सीमा',
    clear_selected: 'चयनित साफ़ करें',
    pricing_control: 'मूल्य निर्धारण नियंत्रण',
    pricing_subtitle: 'उत्पाद बिक्री मूल्य प्रबंधित करें और ऐतिहासिक परिवर्तनों को ट्रैक करें',
    active_selling_prices: 'सक्रिय विक्रय मूल्य',
    search_products_placeholder: 'उत्पाद खोजें...',
    liter_price: 'प्रति लीटर मूल्य',
    glass_price: 'प्रति गिलास मूल्य',
    update_price_btn: 'मूल्य अपडेट करें',
    price_audit_log: 'मूल्य ऑडिट लॉग',
    no_price_changes: 'अभी तक कोई मूल्य परिवर्तन रिकॉर्ड नहीं किया गया है।',
    increase: 'वृद्धि',
    decrease: 'कमी',
    update_selling_price: 'विक्रय मूल्य अपडेट करें',
    product_management: 'उत्पाद प्रबंधन',
    product_mgmt_subtitle: 'अपनी दुकान की सूची और वर्गीकरण प्रबंधित करें',
    add_new_product: 'नया उत्पाद जोड़ें',
    product_details: 'उत्पाद विवरण',
    total_sold: 'कुल बिक्री',
    total_revenue: 'कुल राजस्व',
    no_products_found: 'आपके मानदंडों से मेल खाने वाला कोई उत्पाद नहीं मिला।',
    edit_product: 'उत्पाद संपादित करें',
    create_product: 'उत्पाद बनाएं',
    product_history: 'उत्पाद इतिहास',
    staff_management_subtitle: 'दुकान संचालन के लिए कर्मचारी खाते बनाएं और प्रबंधित करें',
    add_new_staff: 'नया कर्मचारी जोड़ें',
    search_staff_placeholder: 'उपयोगकर्ता नाम या मोबाइल द्वारा कर्मचारी खोजें...',
    staff_info: 'कर्मचारी जानकारी',
    role: 'भूमिका',
    staff_management: 'कर्मचारी प्रबंधन',
    status: 'स्थिति',
    admin: 'एडमिन',
    staff: 'कर्मचारी',
    active: 'सक्रिय',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    edit_staff: 'कर्मचारी संपादित करें',
    enter_username: 'उपयोगकर्ता नाम दर्ज करें',
    enter_password: 'पासवर्ड दर्ज करें',
    delete_user: 'उपयोगकर्ता हटाएं',
    access_denied: 'पहुंच अस्वीकृत',
    access_denied_subtitle: 'केवल प्रशासक ही कर्मचारी सदस्यों को प्रबंधित कर सकते हैं।',
    save_all_changes: 'सभी परिवर्तन सहेजें',
    activity_description: 'गतिविधि विवरण',
    confirm_reset: 'रीसेट की पुष्टि करें',
    yes_reset_now: 'हाँ, अभी रीसेट करें',
    factory_reset: 'फ़ैक्टरी रीसेट',
    password: 'पासवर्ड',
    mobile: 'मोबाइल',
    optional: 'वैकल्पिक',
    not_set: 'सेट नहीं है',
    no_staff_members_found: 'आपकी खोज से मेल खाने वाला कोई कर्मचारी नहीं मिला।',
    create_staff: 'कर्मचारी बनाएं',
    new_entries: 'नई प्रविष्टियाँ',
    all_activities: 'सभी गतिविधियाँ',
    sale: 'बिक्री',
    fresh: 'ताजा',
    opening: 'प्रारंभिक',
    check: 'जाँच',
    adjustment: 'समायोजन',
    scheduled: 'अनुसूचित',
    liter_abbr: 'ली',
    glass_abbr: 'ग्ला',
    rent: 'किराया',
    electricity: 'बिजली',
    staff_salary: 'कर्मचारी वेतन',
    water_bill: 'पानी का बिल',
    maintenance: 'रखरखाव',
    transport: 'परिवहन',
    misc: 'विविध',
    amount: 'राशि',
    profit: 'लाभ',
    products_sold: 'उत्पाद बिके',
    irreversible_action_warning: 'यह क्रिया अपरिवर्तनीय है!',
    at_least_4_chars: 'कम से कम 4 वर्ण',
    username_min_3: 'उपयोगकर्ता नाम कम से कम 3 वर्णों का होना चाहिए।',
    invalid_mobile_10: 'कृपया एक मान्य 10-अंकीय मोबाइल नंबर दर्ज करें।',
    password_mismatch: 'नए पासवर्ड मेल नहीं खाते!',
    password_min_4: 'पासवर्ड कम से कम 4 वर्णों का होना चाहिए।',
    username_exists: 'उपयोगकर्ता नाम पहले से मौजूद है। कृपया दूसरा चुनें।',
    audit_discrepancy: 'ऑडिट विसंगति',
    in_last_audit: 'अंतिम ऑडिट में'
  }
};

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [language, setLanguage] = useState('English');

  useEffect(() => {
    storage.initialize();
    persistence.requestPersistence().catch(console.error);
    const session = storage.get('dsms_session');
    if (session) {
      setUser(session);
      const users = storage.get('dsms_users');
      const currentUser = users.find(u => u.id === session.id);
      if (currentUser?.language) {
        setLanguage(currentUser.language);
      }
    }
    setLoading(false);
  }, []);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    if (user) {
      storage.updateUserLanguage(user.id, lang);
      const session = storage.get('dsms_session');
      if (session) {
        storage.set('dsms_session', { ...session, language: lang });
      }
    }
  };

  const login = (username, password) => {
    const users = storage.get('dsms_users');
    const foundUser = users.find(u => u.username.toLowerCase() === username.toLowerCase() && u.password === password);

    if (foundUser) {
      const userData = {
        id: foundUser.id,
        username: foundUser.username,
        role: foundUser.role,
        mobile: foundUser.mobile,
        language: foundUser.language || 'English'
      };
      setUser(userData);
      setLanguage(userData.language);
      storage.set('dsms_session', userData);
      storage.logActivity(userData, 'LOGIN', 'User logged in');
      return { success: true };
    }
    return { success: false, message: 'invalid_credentials' };
  };

  const logout = () => {
    storage.logActivity(user, 'LOGOUT', 'User logged out');
    setUser(null);
    localStorage.removeItem('dsms_session');
  };

  const updateSession = (newUsername, newMobile) => {
    const session = storage.get('dsms_session');
    if (session) {
      const updated = {
        ...session,
        username: newUsername,
        mobile: newMobile
      };
      setUser(updated);
      storage.set('dsms_session', updated);
    }
  };

  return (
    <AuthContext.Provider value={{ user, login, logout, updateSession, t, language, changeLanguage, loading }}>
      {!loading && children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);
